---

# https://github.com/mediapeers/ansible-role-virtualbox/blob/master/tasks/virtualbox.yml

- name: gather os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: update cache for apt
  apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_os_family == "Debian"

- name: install prereq packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items: "{{ prereq_packages }}"
  tags:
    - install-pkgs
    - prereq

- name: download rhel yum repo
  get_url:
    url: "{{ yum_d_repo }}"
    dest: /etc/yum.repos.d/virtualbox.repo
    mode: 0644
  when:
    - ansible_os_family == "RedHat"

- name: install apt repository
  apt_repository:
    repo: "{{ apt_repo }}"
    state: present
    # filename:
  when:
    - ansible_os_family == "Debian"

- name: add apt key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - "https://www.virtualbox.org/download/oracle_vbox.asc"
  register: apt_key
  until: apt_key | succeeded
  when:
    - ansible_os_family == "Debian"
  tags: apt_keys

- name: install rpm key
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc
  register: add_virtualbox_key
  when:
    - ansible_os_family == "RedHat"

- name: Update repo cache for the new repo
  command: yum makecache -y --disablerepo=* --enablerepo=virtualbox
  when:
    - add_virtualbox_key.changed
    - ansible_os_family == "RedHat"

- name: install bundle repository keys
  shell: "{{ item }}"
  with_items: "{{ repo_keys | default([]) }}"
  failed_when: false
  when:
    - ansible_os_family == "RedHat"

- name: install virtualbox
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items: "{{ virtualbox_package }}"
  tags:
    - install-pkgs

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Download VirtualBox extension pack
  shell: "cd /tmp/ &&  wget http://download.virtualbox.org/virtualbox/{{ virtualbox_version }}.{{ vbox_extension_pack_version }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.{{ vbox_extension_pack_version }}.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace --accept-license=56be48f923303c8cababb0bb4c478284b688ed23f16d775d729b89a2e8e5f9eb /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.{{ vbox_extension_pack_version }}.vbox-extpack"
  when: 'extpack_list.stdout == "Extension Packs: 0"'

- name: add main user to vboxusers group
  user:
    name: "{{ USER_ACCOUNT.NAME }}"
    groups: vboxusers
    append: true
