---
- name: Converge
  hosts: all
  vars:
    configure_vbox_users: true
    vbox_user: root

  pre_tasks:
    - name: set override for ansible_distribution_release
      set_fact:
        virtualbox_dist_release: "buster"
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version | int == 10
  roles:
    - role: ansible-virtualbox
